"""add videos info table

Revision ID: 1850c2442913
Revises: 881938cdae58
Create Date: 2025-12-10 15:14:41.952809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1850c2442913'
down_revision: Union[str, Sequence[str], None] = '881938cdae58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos_info',
    sa.Column('uuid', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('likes_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('dislikes_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.Column('views_count', sa.BIGINT(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_videos_info_author_id'), 'videos_info', ['author_id'], unique=False)
    op.create_index(op.f('ix_videos_info_uuid'), 'videos_info', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_info_uuid'), table_name='videos_info')
    op.drop_index(op.f('ix_videos_info_author_id'), table_name='videos_info')
    op.drop_table('videos_info')
    # ### end Alembic commands ###
